{% set version = "0.1.2" %}

package:
  name: clickhouse-sqlalchemy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/clickhouse-sqlalchemy/clickhouse-sqlalchemy-{{ version }}.tar.gz
  sha256: b50d5031db51f8baa7e4dd32066778ac9097c0993320b4be7edfc2e41a247027

build:
  number: 0
  noarch: python
  script: "pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - pip

  run:
    - python
    - six
    - sqlalchemy
    - requests
    - clickhouse-driver >=0.0.14

test:
  imports:
    - clickhouse_sqlalchemy
    - clickhouse_sqlalchemy.drivers
    - clickhouse_sqlalchemy.drivers.http
    - clickhouse_sqlalchemy.drivers.native
    - clickhouse_sqlalchemy.orm
    - clickhouse_sqlalchemy.sql

about:
  home: https://github.com/xzkostyan/clickhouse-sqlalchemy
  license: MIT
  summary: 'Simple ClickHouse SQLAlchemy Dialect'
  license_file: LICENSE
  license_family: MIT

extra:
  recipe-maintainers:
    - kszucs
    - xzkostyan
