{% set name = "clickhouse-sqlalchemy" %}
{% set version = "0.0.5" %}
{% set sha256 = "169c7ea825dfe64b0b90d0c00ee8e5815e49cae953f168a265989d9634b9dd71" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 2
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - sqlalchemy
    - clickhouse-driver >=0.0.8

  run:
    - python
    - setuptools
    - six
    - sqlalchemy
    - requests
    - clickhouse-driver >=0.0.8

test:
  imports:
    - clickhouse_sqlalchemy
    - clickhouse_sqlalchemy.drivers
    - clickhouse_sqlalchemy.drivers.http
    - clickhouse_sqlalchemy.drivers.native
    - clickhouse_sqlalchemy.orm
    - clickhouse_sqlalchemy.sql

about:
  home: https://github.com/xzkostyan/clickhouse-sqlalchemy
  license: MIT
  summary: 'Simple ClickHouse SQLAlchemy Dialect'
  license_family: MIT

extra:
  recipe-maintainers:
    - kszucs
    - xzkostyan
