{% set version = "0.0.11" %}

package:
  name: clickhouse-sqlalchemy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/clickhouse-sqlalchemy/clickhouse-sqlalchemy-{{ version }}.tar.gz
  sha256: 6dbfa964a4b4938a6c23c5eb381a9f00304f9f2c3e62df6f51beb1ae12dd4526

build:
  number: 0
  noarch: python
  script: "pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - pip

  run:
    - python
    - six
    - sqlalchemy
    - requests
    - clickhouse-driver >=0.0.14

test:
  imports:
    - clickhouse_sqlalchemy
    - clickhouse_sqlalchemy.drivers
    - clickhouse_sqlalchemy.drivers.http
    - clickhouse_sqlalchemy.drivers.native
    - clickhouse_sqlalchemy.orm
    - clickhouse_sqlalchemy.sql

about:
  home: https://github.com/xzkostyan/clickhouse-sqlalchemy
  license: MIT
  summary: 'Simple ClickHouse SQLAlchemy Dialect'
  license_family: MIT

extra:
  recipe-maintainers:
    - kszucs
    - xzkostyan
