{% set version = "0.3.1" %}

package:
  name: clickhouse-sqlalchemy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/clickhouse-sqlalchemy/clickhouse-sqlalchemy-{{ version }}.tar.gz
  sha256: e34a957739064feba561d9336fcb29a4acb68252b714ab36747158e20500b535

build:
  number: 0
  noarch: python
  script: pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - pip

  run:
    - python >=3.6,<4
    - sqlalchemy >=1.4,<1.5
    - requests
    - clickhouse-driver >=0.1.2

test:
  imports:
    - clickhouse_sqlalchemy
    - clickhouse_sqlalchemy.drivers
    - clickhouse_sqlalchemy.drivers.http
    - clickhouse_sqlalchemy.drivers.native
    - clickhouse_sqlalchemy.orm
    - clickhouse_sqlalchemy.sql

about:
  home: https://github.com/xzkostyan/clickhouse-sqlalchemy
  license: MIT
  summary: Simple ClickHouse SQLAlchemy Dialect
  license_file: LICENSE
  license_family: MIT

extra:
  recipe-maintainers:
    - kszucs
    - xzkostyan
