{% set version = "0.3.2" %}

package:
  name: clickhouse-sqlalchemy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/clickhouse-sqlalchemy/clickhouse-sqlalchemy-{{ version }}.tar.gz
  sha256: 267f3a9a1d0d186eb99a41895a684922d31125cea21702cd7dc73af1ccdd10e7

build:
  number: 0
  noarch: python
  script: pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - pip

  run:
    - python >=3.6,<4
    - sqlalchemy >=2.0,<2.1
    - requests
    - clickhouse-driver >=0.1.2

test:
  imports:
    - clickhouse_sqlalchemy
    - clickhouse_sqlalchemy.drivers
    - clickhouse_sqlalchemy.drivers.http
    - clickhouse_sqlalchemy.drivers.native
    - clickhouse_sqlalchemy.orm
    - clickhouse_sqlalchemy.sql

about:
  home: https://github.com/xzkostyan/clickhouse-sqlalchemy
  license: MIT
  summary: Simple ClickHouse SQLAlchemy Dialect
  license_file: LICENSE
  license_family: MIT

extra:
  recipe-maintainers:
    - kszucs
    - xzkostyan
